module.exports = {
	docs: [
		{
			type: "doc",
			id: "index",
		},
        {
            type: "category",
            label: "What's New & Migration",
            collapsible: true,
            collapsed: true,
            link: {
                type: 'generated-index',
                title: "What's New & Migration",
            },
            items: [
                {
                    type: "doc",
                    id: "whats-new"
                },
                {
                    type: "doc",
                    id: "migration"
                },
            ]
        },

        // how to start
        {
            type: "category",
            label: "Getting Started",
            collapsible: true,
            collapsed: false,
            link: {
                type: 'doc',
                id: "guides/initialization",
            },
            items: [
                "guides/installation",
                "guides/cdn-links-list",
                "guides/initialization"
            ]
        },

        // frameworks
        {
            type: "category",
            label: "Integrations",
            collapsible: true,
            collapsed: true,
            link: {
                type: 'doc',
                id: "integrations/howtostart-guides",
            },
            items: [
                {
                    type: "category",
                    label: "React",
                    link: {
                        type: 'doc',
                        id: 'integrations/react/index'
                    },
                    items: [
                        "integrations/react/overview",
                        "integrations/react/installation",
                        "integrations/react/quick-start",
                        "integrations/react/configuration-props",

                        // Data & State Management
                        {
                            type: "category",
                            label: "Data & State Management",
                            link: {
                                type: "doc",
                                id: "integrations/react/state/index"
                            },
                            items: [
                                "integrations/react/state/state-management-basics",
                                "integrations/react/state/redux-toolkit",
                                "integrations/react/state/zustand",
                                "integrations/react/state/mobx",
                                "integrations/react/state/xstate",
                                "integrations/react/state/jotai",
                                "integrations/react/state/valtio",
                                "integrations/react/firebase-integration",
                            ],
                        },
                        // Frameworks
                        {
                            type: "category",
                            label: "Framework Integrations",
                            link: {
                                type: "generated-index",
                                title: "React Scheduler - Framework Integrations",
                            },
                            items: [
                                "integrations/react/nextjs",
                                "integrations/react/remix",
                            ],
                        },
                        "integrations/react/js-scheduler-react",

                        {
                             type: 'doc',
                             id: "integrations/react/copyright"
                        },
                    ]
                },
                "integrations/vue/howtostart-vue",
                "integrations/angular/howtostart-angular",
                "integrations/svelte/howtostart-svelte",
                "integrations/salesforce/howtostart-salesforce",
				"integrations/google-calendar/google-calendar-sync",
				"integrations/firebase/howtostart-firebase",
                {
                    type: "category",
                    label: "Backends",
                    link: {
                        type: 'generated-index',
                        title: 'Backend integrations',
                        keywords: ['Implementing CRUD in different backends', 'dhtmlxScheduler backend integration'],
                    },
                    items: [
                        "integrations/node/howtostart-nodejs",
                        "integrations/dotnet/howtostart-dotnet-core",
                        "integrations/php/howtostart-php-laravel",
                        "integrations/dotnet/howtostart-dotnet",
                        "integrations/php/howtostart-php-slim4",
                        "integrations/php/howtostart-plain-php",
                        "integrations/other/howtostart-ruby",
                    ]
                },
                {
                    type: "category",
                    label: "Legacy",
                    link: {
                        type: 'generated-index',
                        title: 'Legacy integrations',
                    },
                    items: [
                        "integrations/other/howtostart-php",
                        "integrations/other/howtostart-connector",
                        "integrations/other/jquery-integration",
                        "integrations/other/bootstrap",
                        {
                            type: "doc",
                            id: "integrations/legacy/backbone-integration",
                            className: "deprecated",
                        },
                        {
                            type: "doc",
                            id: "integrations/legacy/dhxlayout-integration",
                            className: "deprecated",
                        },
                        "integrations/legacy/dhtmlx-dnd",
                    ]
                },
            ]
        },

		{
			type: "category",
			label: "API",
			collapsible: true,
			collapsed: true,
			link: {
				type: "doc",
				id: "api/api_overview",
			},
			items: [
				// Scheduler methods
				{
					type: "category",
					label: "Methods",
					collapsible: true,
					collapsed: true,
					link: {
						type: "doc",
						id: "api/overview/methods_overview",
					},
					items: [
						"api/method/dataprocessor",
						"api/method/promise",
						"api/method/addevent",
						"api/method/addeventnow",
						"api/method/addmarkedtimespan",
						{
							type: "doc",
							id: "api/method/addsection",
							className: "pro-version",
						},
						"api/method/addshortcut",
						"api/method/alert",
						"api/method/assert",
						"api/method/attachevent",
						"api/method/backbone",
						"api/method/batchupdate",
						"api/method/bind",
						{
							type: "doc",
							id: "api/method/blocktime",
							className: "deprecated",
						},
						"api/method/callevent",
						"api/method/changeeventid",
						"api/method/checkcollision",
						"api/method/checkevent",
						"api/method/checkinmarkedtimespan",
						"api/method/checklimitviolation",
						"api/method/clearall",
						{
							type: "doc",
							id: "api/method/closeallsections",
							className: "pro-version",
						},
						{
							type: "doc",
							id: "api/method/closesection",
							className: "pro-version",
						},
						"api/method/collapse",
						"api/method/confirm",
						"api/method/copy",
						"api/method/createdataprocessor",
						{
							type: "doc",
							id: "api/method/creategridview",
							className: "pro-version",
						},
						{
							type: "doc",
							id: "api/method/createtimelineview",
							className: "pro-version",
						},
						{
							type: "doc",
							id: "api/method/createunitsview",
							className: "pro-version",
						},
						"api/method/defined",
						{
							type: "doc",
							id: "api/method/deleteallsections",
							className: "pro-version",
						},
						"api/method/deleteevent",
						"api/method/deletemarkedtimespan",
						{
							type: "doc",
							id: "api/method/deletesection",
							className: "pro-version",
						},
						"api/method/destructor",
						"api/method/destroycalendar",
						"api/method/detachevent",
						"api/method/edit",
						"api/method/editstop",
						"api/method/endlightbox",
						"api/method/event",
						"api/method/eventremove",
						"api/method/expand",
						"api/method/exporttopdf",
						"api/method/exporttopng",
						"api/method/focus",
						"api/method/formsection",
						"api/method/getactiondata",
						"api/method/getevent",
						{
							type: "doc",
							id: "api/method/geteventenddate",
							className: "deprecated",
						},
						{
							type: "doc",
							id: "api/method/geteventstartdate",
							className: "deprecated",
						},
						{
							type: "doc",
							id: "api/method/geteventtext",
							className: "deprecated",
						},
						"api/method/getevents",
						"api/method/getlabel",
						"api/method/getlightbox",
						"api/method/getrecdates",
						"api/method/getrenderedevent",
						{
							type: "doc",
							id: "api/method/getsection",
							className: "pro-version",
						},
						"api/method/getshortcuthandler",
						"api/method/getstate",
						"api/method/getuserdata",
						"api/method/getview",
						"api/method/hidecover",
						"api/method/hidelightbox",
						"api/method/hidequickinfo",
						"api/method/highlighteventposition",
						"api/method/init",
						"api/method/invertzones",
						"api/method/iscalendarvisible",
						"api/method/isonedayevent",
						"api/method/isviewexists",
						"api/method/linkcalendar",
						"api/method/load",
						"api/method/markcalendar",
						"api/method/marktimespan",
						"api/method/message",
						"api/method/mixin",
						"api/method/modalbox",
						"api/method/openallsections",
						"api/method/opensection",
						"api/method/parse",
						"api/method/plugins",
						"api/method/removeshortcut",
						"api/method/render",
						"api/method/rendercalendar",
						"api/method/renderevent",
						"api/method/resetlightbox",
						{
							type: "doc",
							id: "api/method/scrollunit",
							className: "pro-version",
						},
						"api/method/select",
						"api/method/serialize",
						"api/method/serverlist",
						"api/method/setcurrentview",
						"api/method/setevent",
						{
							type: "doc",
							id: "api/method/seteventenddate",
							className: "deprecated",
						},
						{
							type: "doc",
							id: "api/method/seteventstartdate",
							className: "deprecated",
						},
						{
							type: "doc",
							id: "api/method/seteventtext",
							className: "deprecated",
						},
						"api/method/setlightboxsize",
						"api/method/setloadmode",
						"api/method/setskin",
						"api/method/setuserdata",
						"api/method/showcover",
						"api/method/showevent",
						"api/method/showlightbox",
						"api/method/showquickinfo",
						"api/method/startlightbox",
						"api/method/toical",
						"api/method/tojson",
						"api/method/topdf",
						"api/method/topdfrange",
						"api/method/toxml",
						"api/method/uid",
						{
							type: "doc",
							id: "api/method/unblocktime",
							className: "deprecated",
						},
						"api/method/unmarkcalendar",
						"api/method/unmarktimespan",
						"api/method/unselect",
						"api/method/updatecalendar",
						"api/method/updatecollection",
						"api/method/updateevent",
						"api/method/updateview",
					],
				},
				// Scheduler properties
				{
					type: "category",
					label: "Properties",
					collapsible: true,
					collapsed: true,
					link: {
						type: "doc",
						id: "api/overview/properties_overview",
					},
					items: [
						"api/config/active_link_view",
						"api/config/agenda_end",
						"api/config/agenda_start",
						"api/config/ajax_error",
						"api/config/all_timed",
						"api/config/api_date",
						"api/config/auto_end_date",
						"api/config/buttons_left",
						"api/config/buttons_right",
						"api/config/cascade_event_count",
						"api/config/cascade_event_display",
						"api/config/cascade_event_margin",
						"api/config/check_limits",
						"api/config/collision_limit",
						"api/config/container_autoresize",
						"api/config/csp",
						"api/config/date_format",
						"api/config/day_column_padding",
						"api/config/day_date",
						"api/config/dblclick_create",
						"api/config/default_date",
						"api/config/delay_render",
						"api/config/details_on_create",
						"api/config/details_on_dblclick",
						"api/config/displayed_event_color",
						"api/config/displayed_event_text_color",
						"api/config/display_marked_timespans",
						"api/config/drag_create",
						"api/config/drag_event_body",
						"api/config/drag_highlight",
						"api/config/drag_in",
						"api/config/drag_lightbox",
						"api/config/drag_move",
						"api/config/drag_out",
						"api/config/drag_resize",
						"api/config/edit_on_create",
						"api/config/event_attribute",
						"api/config/event_duration",
						"api/config/first_hour",
						"api/config/fix_tab_position",
						"api/config/full_day",
						"api/config/header",
						"api/config/highlight_displayed_event",
						"api/config/hour_date",
						"api/config/hour_size_px",
						"api/config/icons_edit",
						"api/config/icons_select",
						{
							type: "doc",
							id: "api/config/include_end_by",
							className: "deprecated",
						},
						"api/config/key_nav",
						"api/config/key_nav_step",
						"api/config/last_hour",
						"api/config/left_border",
						"api/config/lightbox",
						"api/config/lightbox_recurring",
						"api/config/limit_drag_out",
						"api/config/limit_end",
						"api/config/limit_start",
						"api/config/limit_time_select",
						"api/config/limit_view",
						"api/config/load_date",
						"api/config/map_end",
						{
							type: "doc",
							id: "api/config/map_error_position",
							className: "deprecated",
						},
						"api/config/map_infowindow_max_width",
						{
							type: "doc",
							id: "api/config/map_initial_position",
							className: "deprecated",
						},
						"api/config/map_initial_zoom",
						"api/config/map_resolve_event_location",
						"api/config/map_resolve_user_location",
						"api/config/map_settings",
						"api/config/map_start",
						{
							type: "doc",
							id: "api/config/map_type",
							className: "deprecated",
						},
						"api/config/map_view_provider",
						"api/config/map_zoom_after_resolve",
						"api/config/mark_now",
						"api/config/max_month_events",
						"api/config/minicalendar",
						{
							type: "doc",
							id: "api/config/min_grid_size",
							className: "pro-version",
						},
						"api/config/min_map_size",
						"api/config/month_date",
						"api/config/month_day",
						"api/config/month_day_min_height",
						{
							type: "doc",
							id: "api/config/multisection",
							className: "pro-version",
						},
						{
							type: "doc",
							id: "api/config/multisection_shift_all",
							className: "pro-version",
						},
						"api/config/multi_day",
						"api/config/multi_day_height_limit",
						"api/config/now_date",
						"api/config/occurrence_timestamp_in_utc",
						"api/config/overwrite_marked_timespans",
						"api/config/parse_exact_format",
						"api/config/positive_closing",
						"api/config/preserve_length",
						"api/config/preserve_scroll",
						"api/config/prevent_cache",
						"api/config/quick_info_detached",
						"api/config/readonly",
						"api/config/readonly_form",
						{
							type: "doc",
							id: "api/config/recurring_overflow_instances",
							className: "deprecated",
						},
						"api/config/recurring_workdays",
						"api/config/repeat_date",
						"api/config/repeat_precise",
						"api/config/resize_month_events",
						"api/config/resize_month_timed",
						"api/config/responsive_lightbox",
						"api/config/rtl",
						"api/config/scroll_hour",
						"api/config/section_delimiter",
						"api/config/select",
						"api/config/separate_short_events",
						"api/config/server_utc",
						"api/config/show_errors",
						"api/config/show_loading",
						"api/config/show_quick_info",
						"api/config/start_on_monday",
						"api/config/time_step",
						{
							type: "doc",
							id: "api/config/timeline_swap_resize",
							className: "pro-version",
						},
						"api/config/tooltip_hide_timeout",
						"api/config/tooltip_offset_x",
						"api/config/tooltip_offset_y",
						"api/config/tooltip_timeout",
						"api/config/touch",
						"api/config/touch_drag",
						"api/config/touch_swipe_dates",
						"api/config/touch_tip",
						"api/config/touch_tooltip",
						"api/config/undo_deleted",
						"api/config/update_render",
						"api/config/use_select_menu_space",
						"api/config/wai_aria_application_role",
						"api/config/wai_aria_attributes",
						{
							type: "doc",
							id: "api/config/week_agenda_select",
							className: "pro-version",
						},
						"api/config/week_date",
						"api/config/wide_form",
						{
							type: "doc",
							id: "api/config/xml_date",
							className: "deprecated",
						},
						"api/config/year_x",
						"api/config/year_y",
					],
				},
				// Scheduler events
				{
					type: "category",
					label: "Events",
					collapsible: true,
					collapsed: true,
					link: {
						type: "doc",
						id: "api/overview/events_overview",
					},
					items: [
						"api/event/onafterbatchupdate",
						"api/event/onaftereventdisplay",
						{
							type: "doc",
							id: "api/event/onafterfoldertoggle",
							className: "pro-version",
						},
						"api/event/onafterlightbox",
						"api/event/onafterquickinfo",
						"api/event/onafterschedulerresize",
						"api/event/onbeforebatchupdate",
						"api/event/onbeforecollapse",
						"api/event/onbeforedrag",
						"api/event/onbeforeeventchanged",
						"api/event/onbeforeeventcreated",
						"api/event/onbeforeeventdelete",
						"api/event/onbeforeeventdisplay",
						"api/event/onbeforeeventdragin",
						"api/event/onbeforeeventdragout",
						"api/event/onbeforeeventpasted",
						"api/event/onbeforeexpand",
						"api/event/onbeforeexternaldragin",
						{
							type: "doc",
							id: "api/event/onbeforefoldertoggle",
							className: "pro-version",
						},
						"api/event/onbeforelightbox",
						"api/event/onbeforeparse",
						"api/event/onbeforequickinfo",
						{
							type: "doc",
							id: "api/event/onbeforesectionrender",
							className: "pro-version",
						},
						"api/event/onbeforetodaydisplayed",
						"api/event/onbeforetooltip",
						"api/event/onbeforeviewchange",
						"api/event/oncellclick",
						"api/event/oncelldblclick",
						"api/event/onclearall",
						"api/event/onclick",
						"api/event/oncollapse",
						"api/event/onconfirmedbeforeeventdelete",
						"api/event/oncontextmenu",
						"api/event/ondatarender",
						"api/event/ondblclick",
						"api/event/ondestroy",
						"api/event/ondragend",
						"api/event/onemptyclick",
						"api/event/onerror",
						"api/event/oneventadded",
						"api/event/oneventcancel",
						"api/event/oneventchanged",
						"api/event/oneventcollision",
						"api/event/oneventcopied",
						"api/event/oneventcreated",
						"api/event/oneventcut",
						"api/event/oneventdeleted",
						"api/event/oneventdragin",
						"api/event/oneventdragout",
						"api/event/oneventdrag",
						"api/event/oneventdropout",
						"api/event/oneventidchange",
						"api/event/oneventloading",
						"api/event/oneventpasted",
						"api/event/oneventsave",
						"api/event/oneventselected",
						"api/event/oneventunselected",
						"api/event/onexpand",
						"api/event/onexternaldragin",
						"api/event/onlightboxbutton",
						"api/event/onlightbox",
						"api/event/onlimitviolation",
						"api/event/onloadend",
						"api/event/onloaderror",
						"api/event/onloadstart",
						"api/event/onlocationerror",
						"api/event/onmousedown",
						"api/event/onmousemove",
						"api/event/onoptionsloadfinal",
						"api/event/onoptionsloadstart",
						"api/event/onoptionsload",
						"api/event/onparse",
						"api/event/onquickinfo",
						"api/event/onsaveerror",
						"api/event/onscaleadd",
						"api/event/onscaledblclick",
						"api/event/onschedulerready",
						"api/event/onschedulerresize",
						"api/event/ontemplatesready",
						"api/event/ontimelinecreated",
						"api/event/onviewchange",
						"api/event/onviewmoreclick",
						{
							type: "doc",
							id: "api/event/onxle",
							className: "deprecated",
						},
						{
							type: "doc",
							id: "api/event/onxls",
							className: "deprecated",
						},
						"api/event/onxscaleclick",
						"api/event/onxscaledblclick",
						"api/event/onyscaleclick",
						"api/event/onyscaledblclick",
					],
				},
				// // Scheduler templates
				{
					type: "category",
					label: "Templates",
					collapsible: true,
					collapsed: true,
					link: {
						type: "doc",
						id: "api/overview/templates_overview",
					},
					items: [
						"api/template/agenda_date",
						"api/template/agenda_day",
						"api/template/agenda_text",
						"api/template/agenda_time",
						"api/template/api_date",
						"api/template/calendar_date",
						"api/template/calendar_month",
						"api/template/calendar_scale_date",
						"api/template/calendar_time",
						"api/template/day_date",
						"api/template/day_scale_date",
						"api/template/drag_marker_class",
						"api/template/drag_marker_content",
						"api/template/event_bar_date",
						"api/template/event_bar_text",
						"api/template/event_class",
						"api/template/event_date",
						"api/template/event_header",
						"api/template/event_text",
						"api/template/format_date",
						"api/template/hour_scale",
						"api/template/lightbox_header",
						"api/template/load_format",
						{
							type: "doc",
							id: "api/template/marker_date",
							className: "deprecated",
						},
						{
							type: "doc",
							id: "api/template/marker_text",
							className: "deprecated",
						},
						"api/template/map_info_content",
						"api/template/map_date",
						"api/template/map_text",
						"api/template/map_time",
						"api/template/month_date_class",
						"api/template/month_date",
						"api/template/month_day",
						"api/template/month_events_link",
						"api/template/month_scale_date",
						"api/template/parse_date",
						"api/template/time_picker",
						"api/template/time_slot_class",
						"api/template/time_slot_text",
						"api/template/tooltip_date_format",
						"api/template/tooltip_text",
						"api/template/quick_info_content",
						"api/template/quick_info_date",
						"api/template/quick_info_title",
						{
							type: "doc",
							id: "api/template/week_agenda_date",
							className: "pro-version",
						},
						{
							type: "doc",
							id: "api/template/week_agenda_event_text",
							className: "pro-version",
						},
						{
							type: "doc",
							id: "api/template/week_agenda_scale_date",
							className: "pro-version",
						},
						"api/template/week_date_class",
						"api/template/week_date",
						"api/template/week_scale_date",
						{
							type: "doc",
							id: "api/template/xml_date",
							className: "deprecated",
						},
						{
							type: "doc",
							id: "api/template/xml_format",
							className: "deprecated",
						},
						"api/template/year_date",
						"api/template/year_month",
						"api/template/year_scale_date",
						"api/template/year_tooltip",
						{
							type: "doc",
							id: "api/template/gridname_date",
							className: "pro-version",
						},
						{
							type: "doc",
							id: "api/template/gridname_field",
							className: "pro-version",
						},
						{
							type: "doc",
							id: "api/template/gridname_full_date",
							className: "pro-version",
						},
						{
							type: "doc",
							id: "api/template/gridname_single_date",
							className: "pro-version",
						},
						{
							type: "doc",
							id: "api/template/timelinename_cell_class",
							className: "pro-version",
						},
						{
							type: "doc",
							id: "api/template/timelinename_cell_value",
							className: "pro-version",
						},
						{
							type: "doc",
							id: "api/template/timelinename_date",
							className: "pro-version",
						},
						{
							type: "doc",
							id: "api/template/timelinename_row_class",
							className: "pro-version",
						},
						{
							type: "doc",
							id: "api/template/timelinename_scalex_class",
							className: "pro-version",
						},
						{
							type: "doc",
							id: "api/template/timelinename_scaley_class",
							className: "pro-version",
						},
						{
							type: "doc",
							id: "api/template/timelinename_scale_date",
							className: "pro-version",
						},
						{
							type: "doc",
							id: "api/template/timelinename_scale_label",
							className: "pro-version",
						},
						{
							type: "doc",
							id: "api/template/timelinename_second_scalex_class",
							className: "pro-version",
						},
						{
							type: "doc",
							id: "api/template/timelinename_second_scale_date",
							className: "pro-version",
						},
						{
							type: "doc",
							id: "api/template/timelinename_tooltip",
							className: "pro-version",
						},
						{
							type: "doc",
							id: "api/template/unitsname_date",
							className: "pro-version",
						},
						{
							type: "doc",
							id: "api/template/unitsname_scale_text",
							className: "pro-version",
						},
					],
				},
				// // Scheduler others
				{
					type: "category",
					label: "Others",
					collapsible: true,
					collapsed: true,
					link: {
						type: "doc",
						id: "api/overview/others_overview",
					},
					items: [
						"api/other/ajax",
						"api/other/config",
						"api/other/date",
						"api/other/env",
						"api/other/i18n",
						"api/other/ical",
						"api/other/json",
						"api/other/keys",
						"api/other/locale",
						"api/other/matrix",
						"api/other/skin",
						"api/other/templates",
						"api/other/tooltip",
						"api/other/version",
						"api/other/xy",
					],
				},
			],
		},

		// Views
		{
			type: "category",
			label: "Views",
			collapsible: true,
			collapsed: true,
			link: {
				type: "doc",
				id: "views/index",
			},
			items: [
				"views/day",
				"views/week",
				"views/month",
				"views/agenda",
				"views/agenda-legacy",
				"views/map",
				{
					type: "doc",
					id: "views/timeline",
					className: "pro-version",
				},
				{
					type: "doc",
					id: "views/weekagenda",
					className: "pro-version",
				},
				{
					type: "doc",
					id: "views/units",
					className: "pro-version",
				},
				"views/year",
				{
					type: "doc",
					id: "views/grid",
					className: "pro-version",
				},
				{
					type: "category",
					label: "View Templates",
					link: {
						type: "generated-index",
						title: "View Templates",
					},
					items: [
						"views/day-view-templates",
						"views/week-view-templates",
						"views/month-view-templates",
						"views/agenda-view-templates",
						{ type: "doc", id: "views/agenda-view-templates-legacy", className: "deprecated" },
						"views/map-view-templates",
						{ type: "doc", id: "views/timeline-view-templates", className: "pro-version" },
						{ type: "doc", id: "views/weekagenda-view-templates", className: "pro-version" },
						{ type: "doc", id: "views/units-view-templates", className: "pro-version" },
						"views/year-view-templates",
						{ type: "doc", id: "views/grid-view-templates", className: "pro-version" },
					],
				},
			],
		},
		//Guides
		{
			type: "category",
			label: "Guides",
			collapsible: true,
			collapsed: true,
			link: {
				type: "doc",
				id: "guides/index",
			},
			items: [
				"guides/editions-comparison",
				{
					type: "category",
					label: "Configuring Scheduler",
					link: {
						type: "doc",
						id: "guides/configuring-the-scheduler"
					},
					items: [
						"guides/configuration",
						"guides/scheduler-markup",
						{
							type: "doc",
							id: "guides/multiple-per-page",
							className: "pro-version",
						},
						"guides/rtl-mode",
						"guides/localization",
						"guides/accessibility",
						"guides/keyboard-navigation",
					],
				},
				{
					type: "category",
					label: "Loading and Storing Data",
					link: {
						type: "doc",
						id: "guides/loading-and-storing-data"
					},
					items: [
						{
							type: "category",
							label: "Loading Data",
							link: {
								type: "doc",
								id: "guides/loading-data",
							},
							items: ["guides/data-formats"],
						},
						"guides/server-integration",
						"guides/troubleshooting",
						"guides/app-security",
					],
				},
				"guides/recurring-events",
				{
					type: "category",
					label: "Configuring Views",
					link: {
						type: "doc",
						id: "guides/config-views"
					},
					items: [
						"guides/custom-scales",
						"guides/custom-views",
						"guides/limits",
					],
				},
				{
					type: "category",
					label: "Configuring the Lightbox",
					link: {
						
						type: "doc",
						id: "guides/configuring-the-lightbox",
				
					},
					items: [
						"guides/lightbox-editors",
						{
							type: "category",
							label: "Lightbox Editors Manipulations",
							link: {
								type: "doc",
								id: "guides/lightbox-editors-manipulations",
							},
							items: [
								"guides/textarea",
								"guides/time",
								"guides/select",
								"guides/template",
								"guides/multiselect",
								"guides/checkbox",
								"guides/radio",
								"guides/combo",
							],
						},
						"guides/custom-lightbox-editor",
						"guides/custom-details-form",
						"guides/changing-lightbox-buttons",
					],
				},
				{
					type: "category",
					label: "Managing Scheduler Events",
					link: {
						type: "doc",
						id: "guides/managing-events"
					},
					items: [
						"guides/event-object-operations",
						"guides/adding-events",
						"guides/filtering",
						
						"guides/recurring-events",
						"guides/recurring-events-legacy",
						"guides/readonly",
						"guides/validation",
						"guides/collisions",
					],
				},
				{
					type: "category",
					label: "Customizing Events",
					link: {
						type: "doc",
						id: "guides/customizing-events"
					},
					items: [
						"guides/custom-events-display",
						"guides/custom-events-color",
						"guides/custom-events-content",
						"guides/tooltips",
						{ type: "doc", id: "guides/tooltips-legacy", className: "deprecated" },
						"guides/customizing-edit-select-bars",
						"guides/sizing",
						{ type: "doc", id: "guides/sizing-legacy", className: "deprecated" },
					],
				},
				{
					type: "category",
					label: "Export and Import",
					link: {
						type: "doc",
						id: "export/index"
					},
					items: [

						
						{
							type: "category",
							label: "Export to PDF",
							link: {
								type: "doc",
								id: "export/pdf",
							},
							items: [
								{ type: "doc", id: "export/pdf-legacy", className: "deprecated" },
								"export/pdf-multi",
							],
						},
						"export/png",
						"export/excel",
						{
							type: "category",
							label: "Data Serialization to XML, JSON, iCal",
							link: {
								type: "doc",
								id: "export/serialization",
							},
							items: [
								{
									type: "doc",
									id: "guides/ical-export-import",
									className: "deprecated",
								},
							],
						},
					],
				},
				{
					type: "category",
					label: "Appearance and Styling",
					link: {
						type: "doc",
						id: "guides/appearance-and-styling"
					},
					items: [
						"guides/skins",
						"guides/templates",
						"guides/custom-skins",
						"guides/popups-and-modals",
						"guides/mini-calendar-templates",
						"guides/common-templates",
					],
				},
				{
					type: "category",
					label: "Working with Dates",
					link: {
						type: "doc",
						id: "guides/dates-in-scheduler"
					},
					items: ["guides/date-formats", "guides/settings-format"],
				},
				{
					type: "category",
					label: "Special Extensions and Editions",
					link: {
						type: "doc",
						id: "guides/special-extensions"
					},
					items: [
						"guides/minicalendar",
						"guides/touch-support",
						"guides/multiuser-live-updates",
						"guides/multiple-users",
						"guides/drag-between",
						"guides/quick-info",
					],
				},
				"guides/user-interface",
				"guides/extensions-list"
			],
		},
		{
			type: "doc",
			id: "guides/video-guides",
		},
		{
			type: "doc",
			id: "copyright",
		},
		{
			type: "doc",
			id: "faq",
		},
	],
};
